### PR TITLE
fix(ui): reset the form after submission so that the fields are pristine and not invalid

### PR DESCRIPTION
**Pull request by Gerromie**
# Story

It was reported in issue #234 that it was not possible to add a new REST Endpoint after creating one. I was not able to replicate that, but I did see a problem.

## Changes

1. Reset the form after submissions as it was noticed that the fields were red immediately (issue #234)
2. Disabled the Add button when editing an existing endpoint (issue #233)

## Tests

Tested while using the app in development mode.

### CODE REVIEW

**Review by tibco-tdinh — APPROVED** [review]

**Comment by Gerromie** [comment]
In my efforts to correct these two issues, I noticed that the issue had been propagated to the other tabs, too, or perhaps originated there and was copied over when the pattern was reused. I'm going to expand the scope of this pull request to fix those as well.

Note: The `ige-protocols` component could utilize a refactor. The class has three form implementations in it. I think a refactor that should be done would make the supported protocols into child components. This way, the child components could handle their own data and one component would not need to know about all possible protocols.

@tibco-tdinh , I also found issues with the `Resources` tab, but I think this is a work in progress. Let's chat about what I saw.

**Comment by magallardo** [comment]
We need to start refactoring as much as possible.  The configuration  panel
should be refactored for all the common information like name, debug level,
etc.

**Review by tibco-tdinh — APPROVED** [review]
Still looks good.

**Comment by tibco-tdinh** [comment]
> In my efforts to correct these two issues, I noticed that the issue had been propagated to the other tabs, too, or perhaps originated there and was copied over when the pattern was reused. I'm going to expand the scope of this pull request to fix those as well.
> 
> Note: The `ige-protocols` component could utilize a refactor. The class has three form implementations in it. I think a refactor that should be done would make the supported protocols into child components. This way, the child components could handle their own data and one component would not need to know about all possible protocols.
> 
> @tibco-tdinh , I also found issues with the `Resources` tab, but I think this is a work in progress. Let's chat about what I saw.

Yes, the Resources tab is still a work in progress. The latest Python Pipe activity modifies it with a few more features.

**Pull request merged**
